### ISSUE TITLE
allowRightClickInfo doesn't work

### ISSUE THREAD

**Issue by DarkVillager** [Lileep/PixelmonDetector#6]
I changed the config to allow me to right click for info. But it doesn't work.

Log:
https://paste.atlauncher.com/view/ed6b5944-63b0-42f2-91cc-ba14773e76b5

Config:
```toml

[general]
	#Whether to allow Pixelmon Detector
	allowDetector = true
	#Whether to allow right click to show Pokemon details like how Ras's lens do when hands are empty
	allowRightClickInfo = true
```
